#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+    at the root with a curl GET request.
#
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html

sudo touch /etc/nginx/html/index.htm
chmod 666 index.html
echo "Hello World!" > /etc/nginx/html/index.html

sudo touch /etc/nginx/html/404.html
chmod 666 /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

chmod 666 /etc/nginx/sites-available/default
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
