#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get update
sudo apt-get install haproxy

sudo touch /etc/default/haproxy
sudo chmod 666 /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy

sudo mkdir /etc/haproxy
sudo touch /etc/haproxy/haproxy.cfg
sudo mv /etc/haproxy/haproxy.cfg{,.original}

sudo chmod 666 /etc/haproxy/haproxy.cfg
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
    
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    
listen appname 0.0.0.0:80
	mode http
	stats enable
	stats uri /haproxy?stats
	stats realm Strictly\ Private
	stats auth A_Username:YourPassword
	stats auth Another_User:passwd
	balance roundrobin
	option httpclose
	option forwardfor
    server 21812-web-01 35.170.73.199:80 check
    server 21812-web-02 44.200.22.149:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
