#!/usr/bin/env bash
# Script that sets the port 80
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo service nginx restart
