#!/usr/bin/env bash
# Displays Best School 10 times with while loop
# If statement prints Hi on 9th line

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
