#!/usr/bin/env bash
# Loops from 1 to 10
# Displays bad luck for the 4th loop iteration
# Displays good luck for the 8th loop iteration
# Displays Best School for the other iterations

$i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
