#!/usr/bin/env bash
# Script that starts nginx as nginx user
sudo chmod 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo pkill -9 apache
sudo nginx -c "service nginx restart"
